// Artifact.swift
// A2AClient
//
// Agent2Agent Protocol - Artifact Definitions

import Foundation

/// Represents an output artifact generated by an agent during task processing.
///
/// Artifacts are tangible deliverables produced by the agent, such as generated files,
/// code, or structured data results.
public struct Artifact: Codable, Sendable, Equatable, Identifiable {
    /// Unique identifier for this artifact.
    public let artifactId: String

    /// Optional human-readable name for the artifact.
    public let name: String?

    /// Optional description of the artifact.
    public let description: String?

    /// Content parts comprising this artifact.
    public let parts: [Part]

    /// Optional metadata associated with this artifact.
    public let metadata: [String: AnyCodable]?

    /// Optional extension URIs for this artifact.
    public let extensions: [String]?

    public var id: String { artifactId }

    public init(
        artifactId: String = UUID().uuidString,
        name: String? = nil,
        description: String? = nil,
        parts: [Part],
        metadata: [String: AnyCodable]? = nil,
        extensions: [String]? = nil
    ) {
        self.artifactId = artifactId
        self.name = name
        self.description = description
        self.parts = parts
        self.metadata = metadata
        self.extensions = extensions
    }

    private enum CodingKeys: String, CodingKey {
        case artifactId
        case name
        case description
        case parts
        case metadata
        case extensions
    }
}

// MARK: - Convenience Extensions

extension Artifact {
    /// Creates an artifact with text content.
    public static func text(
        _ text: String,
        name: String? = nil,
        description: String? = nil
    ) -> Artifact {
        Artifact(
            name: name,
            description: description,
            parts: [.text(text)]
        )
    }

    /// Creates an artifact with file content.
    public static func file(
        data: Data,
        fileName: String,
        mediaType: String? = nil,
        description: String? = nil
    ) -> Artifact {
        Artifact(
            name: fileName,
            description: description,
            parts: [.file(data: data, name: fileName, mediaType: mediaType)]
        )
    }

    /// Creates an artifact with structured data.
    public static func data(
        _ data: [String: AnyCodable],
        name: String? = nil,
        description: String? = nil
    ) -> Artifact {
        Artifact(
            name: name,
            description: description,
            parts: [.data(data)]
        )
    }

    /// Returns all text content from this artifact concatenated.
    public var textContent: String {
        parts.compactMap { $0.text }.joined(separator: "\n")
    }
}
